name = "StructDatabaseMapping"
uuid = "66daddfc-c305-4fd9-8f84-fb59daccc546"
authors = ["Luciano Rolando Lorenti <lucianolorenti@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
julia = "1"
Requires = "1"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
